version: '3.5'

services:
    mysql:
        restart: always

    wordpress:
        volumes:
            - ./wordpress:/var/www/html:ro
        restart: always

    nginx:
        image: nginx:1.13
        depends_on:
            - wordpress
        volumes:
            - ./nginx/andreduvoisin.com.conf:/etc/nginx/conf.d/andreduvoisin.com.conf:ro
        ports:
            - "80:80"
        restart: always

    certbot:
        image: certbot/dns-route53
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
        restart: always
        environment:
            AWS_ACCESS_KEY_ID: AKIAJSKKVGXD4ZGKQLXQ
            AWS_SECRET_ACCESS_KEY: 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
