version: '3.5'

services:
    mysql:
        container_name: andreduvoisin-web_mysql
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/andrygzc_wp117.sql:/docker-entrypoint-initdb.d/andrygzc_wp117.sql:ro
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: andrygzc_wp117
            MYSQL_USER: andrygzc_wp117
            MYSQL_PASSWORD: "]ZkAS24P2!"

    wordpress:
        container_name: andreduvoisin-web_wordpress
        image: wordpress:4.4
        depends_on:
            - mysql
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: andrygzc_wp117
            WORDPRESS_DB_USER: andrygzc_wp117
            WORDPRESS_DB_PASSWORD: "]ZkAS24P2!"

volumes:
    mysql-data:
