version: '3.5'

services:
    mysql:
        volumes:
            - ./mysql/andrygzc_wp117.sql:/docker-entrypoint-initdb.d/andrygzc_wp117.sql
            - ./mysql/localhost-migrate.sql:/docker-entrypoint-initdb.d/localhost-migrate.sql

    wordpress:
        volumes:
            - ./wordpress:/var/www/html
        ports:
            - "8080:80"
