version: '3.5'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: andrygzc_wp117
            MYSQL_USER: andrygzc_wp117
            MYSQL_PASSWORD: "]ZkAS24P2!"

    wordpress:
        image: wordpress:4.4
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - mysql
        restart: always
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: andrygzc_wp117
            WORDPRESS_DB_USER: andrygzc_wp117
            WORDPRESS_DB_PASSWORD: "]ZkAS24P2!"

volumes:
    mysql-data:
