version: '3.5'

services:
    mysql:
        restart: always

    wordpress:
        restart: always

    nginx:
        image: nginx:1.13
        depends_on:
            - wordpress
        volumes:
            - ./nginx/andreduvoisin.com.conf:/etc/nginx/conf.d/andreduvoisin.com.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
        ports:
            - "80:80"
            - "443:443"
        restart: always

    certbot:
        image: certbot/dns-route53
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - /var/logs/letsencrypt:/var/logs/letsencrypt
        environment:
            AWS_ACCESS_KEY_ID: AKIAJSKKVGXD4ZGKQLXQ
            AWS_SECRET_ACCESS_KEY: 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
        # command: certonly --dns-route53 --noninteractive --agree-tos --email anduv13@gmail.com --server https://acme-v02.api.letsencrypt.org/directory -d andreduvoisin.com -d *.andreduvoisin.com
        command: renew
