version: '3.6'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - mysql
        image: wordpress:4.9.5
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

volumes:
    mysql-data:
